# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 04:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('rush', '0001_initial'), ('rush', '0002_auto_20171024_0436'), ('rush', '0003_auto_20171024_0438'), ('rush', '0004_auto_20171024_0440'), ('rush', '0005_auto_20171024_0445')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RushEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('room_number', models.CharField(help_text='Ex. "Backcourt" for GSU Background or "209" for PHO 209', max_length=20, verbose_name='Room Number or Name')),
                ('room_long_name', models.CharField(help_text='Example: Photonics Center Auditorium (for PHO 206)', max_length=50, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('description', models.TextField(help_text='Use HTML tags to bold or italicize text.Note: Use the same description for both infosessions.')),
            ],
        ),
        migrations.CreateModel(
            name='RushEventLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('abbreviation', models.CharField(blank=True, default='', help_text='Leave blank for something like "BU Beach"', max_length=5)),
                ('lat', models.DecimalField(decimal_places=6, help_text='Put building name into https://www.latlong.net/ for lat/lng', max_digits=8, verbose_name='Latitude')),
                ('lng', models.DecimalField(decimal_places=6, help_text='See above', max_digits=8, verbose_name='Longitude')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Event Location',
            },
        ),
        migrations.AddField(
            model_name='rushevent',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rush.RushEventLocation'),
        ),
        migrations.AlterModelOptions(
            name='rushevent',
            options={'ordering': ['start_time'], 'verbose_name': 'Event'},
        ),
        migrations.AlterField(
            model_name='rushevent',
            name='room_number',
            field=models.CharField(help_text='Ex. "Backcourt" for GSU Backcourt or "209" for PHO 209', max_length=20, null=True, verbose_name='Room Number or Name'),
        ),
        migrations.AddField(
            model_name='rushevent',
            name='is_open_rush',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rushevent',
            name='description',
            field=models.TextField(help_text='Use HTML tags to bold or italicize text.\nNote: Use the same description for both infosessions.'),
        ),
        migrations.AlterField(
            model_name='rushevent',
            name='room_long_name',
            field=models.CharField(blank=True, default='', help_text='Example: Photonics Center Auditorium (for PHO 206)', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rushevent',
            name='room_number',
            field=models.CharField(blank=True, default='', help_text='Ex. "Backcourt" for GSU Backcourt or "209" for PHO 209', max_length=20, verbose_name='Room Number or Name'),
            preserve_default=False,
        ),
    ]
