# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-18 00:38
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rush', '0001_squashed_0005_auto_20171024_0445'),
    ]

    operations = [
        migrations.CreateModel(
            name='RushApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('address', models.CharField(max_length=15)),
                ('gpa', models.CharField(max_length=5)),
                ('application_answers', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='RushProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.CharField(blank=True, max_length=8, null=True)),
                ('semester', models.CharField(max_length=3)),
                ('phone_number', models.CharField(max_length=11)),
                ('grade', models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior')], max_length=2)),
                ('channel', models.CharField(max_length=30)),
                ('major_schools', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=3), size=None)),
                ('majors', models.CharField(max_length=100)),
                ('minor_schools', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=3), size=None)),
                ('minors', models.CharField(max_length=100)),
                ('events_attended', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None)),
                ('submitted_application', models.BooleanField()),
                ('interview_wave', models.PositiveSmallIntegerField()),
                ('interview_prelim_yes', models.PositiveSmallIntegerField()),
                ('interview_prelim_no', models.PositiveSmallIntegerField()),
                ('interview_prelim_abstain', models.PositiveSmallIntegerField()),
                ('interview_prelim_deliberate', models.BooleanField()),
                ('interview_final_yes', models.PositiveSmallIntegerField()),
                ('interview_final_no', models.PositiveSmallIntegerField()),
                ('interview_final_abstain', models.PositiveSmallIntegerField()),
                ('given_bid', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='rushevent',
            name='description',
            field=models.TextField(help_text='Use HTML tags to bold or italicize text.<br>Note: Use the same description for both infosessions.'),
        ),
        migrations.AlterField(
            model_name='rushevent',
            name='is_open_rush',
            field=models.BooleanField(verbose_name='Open Rush?'),
        ),
        migrations.AlterField(
            model_name='rushevent',
            name='room_long_name',
            field=models.CharField(blank=True, help_text='Example: Photonics Center Auditorium (for PHO 206)', max_length=50, verbose_name='Room Name (Long)'),
        ),
        migrations.AlterField(
            model_name='rusheventlocation',
            name='abbreviation',
            field=models.CharField(blank=True, help_text='Leave blank for something like "BU Beach"', max_length=5),
        ),
        migrations.AddField(
            model_name='rushapplication',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='rush.RushProfile'),
        ),
    ]
