# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rush', '0002_auto_20171024_0436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rusheventlocation',
            name='abbreviation',
            field=models.CharField(help_text='Leave blank for something like "BU Beach"', max_length=5, null=True),
        ),
    ]
