# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-18 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rush', '0002_auto_20180118_0038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rushprofile',
            name='minor_schools',
        ),
        migrations.AlterField(
            model_name='rushprofile',
            name='email',
            field=models.CharField(default='', max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rushprofile',
            name='given_bid',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='rushprofile',
            name='interview_final_abstain',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rushprofile',
            name='interview_final_no',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rushprofile',
            name='interview_final_yes',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rushprofile',
            name='interview_prelim_abstain',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rushprofile',
            name='interview_prelim_deliberate',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='rushprofile',
            name='interview_prelim_no',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rushprofile',
            name='interview_prelim_yes',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rushprofile',
            name='interview_wave',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rushprofile',
            name='minors',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rushprofile',
            name='submitted_application',
            field=models.BooleanField(default=False),
        ),
    ]
