# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-01 15:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rush', '0004_auto_20180118_0219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rushapplication',
            name='application_answers',
        ),
    ]
