# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rush', '0004_auto_20171024_0440'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rusheventlocation',
            options={'ordering': ['name'], 'verbose_name': 'Event Location'},
        ),
        migrations.AddField(
            model_name='rushevent',
            name='is_open_rush',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rushevent',
            name='description',
            field=models.TextField(help_text='Use HTML tags to bold or italicize text.\nNote: Use the same description for both infosessions.'),
        ),
        migrations.AlterField(
            model_name='rushevent',
            name='room_long_name',
            field=models.CharField(blank=True, default='', help_text='Example: Photonics Center Auditorium (for PHO 206)', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rushevent',
            name='room_number',
            field=models.CharField(blank=True, default='', help_text='Ex. "Backcourt" for GSU Backcourt or "209" for PHO 209', max_length=20, verbose_name='Room Number or Name'),
            preserve_default=False,
        ),
    ]
