# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-02 23:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rush', '0007_auto_20180201_1541'),
        ('rush', '0005_auto_20180131_1720'),
    ]

    operations = [
    ]
