# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-03 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rush', '0009_auto_20180203_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rushprofile',
            name='interview_final_abstain',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rushprofile',
            name='interview_final_no',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rushprofile',
            name='interview_final_yes',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rushprofile',
            name='interview_prelim_abstain',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rushprofile',
            name='interview_prelim_no',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rushprofile',
            name='interview_prelim_yes',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rushprofile',
            name='interview_wave',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
