# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-09 02:28
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rush', '0010_auto_20180203_0315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rushapplication',
            options={'ordering': ['timestamp'], 'verbose_name': 'Application'},
        ),
        migrations.AlterModelOptions(
            name='rushprofile',
            options={'ordering': ['last_name'], 'verbose_name': 'Rush Profile'},
        ),
        migrations.AlterField(
            model_name='rushapplication',
            name='application_answers',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rushapplication',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='rush_pics/'),
        ),
        migrations.AlterField(
            model_name='rushapplication',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='rush_resumes/'),
        ),
    ]
