# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-14 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rush', '0011_auto_20180209_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rushapplication',
            name='address',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='rushapplication',
            name='gpa',
            field=models.CharField(default=0, max_length=5),
        ),
    ]
