# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 16:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brothers', '0003_auto_20171021_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='SFGMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=45)),
                ('bio', models.TextField()),
                ('brother', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='brothers.Brother')),
            ],
        ),
    ]
