# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfg', '0002_auto_20171022_0441'),
    ]

    operations = [
        migrations.CreateModel(
            name='sfgPlacement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm_name', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=20)),
            ],
        ),
    ]
