# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brother',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=8, null=True, unique=True)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('class_name', models.CharField(max_length=8)),
                ('year', models.CharField(max_length=4)),
                ('major_school', models.CharField(max_length=255)),
                ('major', models.CharField(max_length=255)),
                ('minor_school', models.CharField(max_length=255)),
                ('minor', models.CharField(max_length=255)),
                ('linkedin', models.URLField(max_length=300)),
                ('status', models.CharField(choices=[('AC', 'Active'), ('IA', 'Inactive'), ('AL', 'Alumni'), ('LO', 'LOA')], max_length=2)),
                ('eye2eye', models.BooleanField(default=False)),
                ('nccg', models.BooleanField(default=False)),
            ],
        ),
    ]
