# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 03:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brothers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EBoardMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=45)),
                ('order', models.IntegerField()),
                ('brother', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='brothers.Brother')),
            ],
        ),
    ]
