# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 21:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brothers', '0003_auto_20171021_2041'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FAQ',
        ),
    ]
