# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brothers', '0003_auto_20171021_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eboardmember',
            name='order',
        ),
        migrations.AlterField(
            model_name='brother',
            name='major_school',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
