# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 18:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brothers', '0004_delete_faq'),
        ('brothers', '0004_auto_20171022_0441'),
    ]

    operations = [
    ]
