# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-18 00:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brothers', '0005_merge_20171031_0209'),
        ('brothers', '0005_merge_20171024_0419'),
        ('brothers', '0005_merge_20171022_1850'),
    ]

    operations = [
    ]
