# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-14 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('brew_type', models.CharField(choices=[('ES', 'Espresso'), ('AM', 'Americano')], max_length=2)),
                ('brew_temp', models.IntegerField()),
                ('brew_pressure', models.IntegerField()),
                ('brew_time', models.IntegerField()),
            ],
        ),
    ]
