# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 02:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brothers', '0005_merge_20171022_1850'),
        ('eye2eye', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('body', models.TextField()),
                ('footnotes', models.TextField()),
                ('slug', models.SlugField()),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='brothers.Brother')),
            ],
        ),
    ]
