# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brothers', '0005_merge_20171022_1850'),
        ('eye2eye', '0002_blogarticle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogarticle',
            options={'verbose_name': 'Blog Article', 'verbose_name_plural': 'Blog Articles'},
        ),
        migrations.RemoveField(
            model_name='blogarticle',
            name='author',
        ),
        migrations.AddField(
            model_name='blogarticle',
            name='author',
            field=models.ManyToManyField(to='brothers.Brother'),
        ),
    ]
