# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 03:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
from brothers.models import Brother


class Migration(migrations.Migration):

    dependencies = [
        ('brothers', '0005_merge_20171022_1850'),
        ('eye2eye', '0003_auto_20171023_0257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogarticle',
            name='author',
        ),
        migrations.AddField(
            model_name='blogarticle',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='brothers.Brother'),
            preserve_default=False,
        ),
    ]
