# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 03:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eye2eye', '0004_auto_20171023_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogarticle',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brothers.Brother'),
        ),
    ]
