# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-18 00:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eye2eye', '0005_auto_20171023_0308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogarticle',
            options={'ordering': ['-created_at'], 'verbose_name': 'Blog Article', 'verbose_name_plural': 'Blog Articles'},
        ),
    ]
